import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { Toaster } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex min-h-screen flex-col bg-stone-200'>
					<nav className='flex items-center justify-between p-4 bg-stone-800 text-white'>
						<ul className='flex gap-4'>
							<li>
								<Link href='/'>Inicio</Link>
							</li>
							<li>
								<Link href='/products'>Productos</Link>
							</li>
							<li>
								<Link href='/invoices'>Facturas</Link>
							</li>
						</ul>
					</nav>
					<div className='md:container max-sm:px-5  mt-8 '>{children}</div>
				</div>

				<Toaster richColors expand={true} />
			</body>
		</html>
	)
}
